git push origin actas
git push origin arbitros
git push origin circulares
git push origin clubes
git push origin commons
git push origin delegaciones
git push origin divisiones
git push origin documentaciones
git push origin elo
git push origin federados
git push origin habilitados
git push origin inscripciones
git push origin jugadores
git push origin logins
git push origin monitores
git push origin reglamentos
git push origin torneos
git push origin transeuntes
